config/routes.rb
Rails.application.routes.draw do
  resources :users
  resource :session
  
  post "/guestAccount", to: "users#guest_account", as: :guest_account
  
  root to: "static#root"
  get "/notes", to: "static#backbone", as: "backbone"
  resources :sharings, only: :show, controller: "api/sharings"
  
  namespace :api, defaults: { format: :json } do
    resources :notebooks do
      resources :notes
    end
    
    resources :sharings, only: [:create, :update]
    resources :taggings
  end
end

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <ul>
  <% flash[:errors].each do |error| %>
    <li><%= error %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/_user_links.html.erb
<% if current_user %>
  <li><%= button_to "Sign Out: " + current_user.username,
                session_url,
                method: :delete,
                class: "btn btn-danger navbar-btn" %></li>
<% else %>
  <li>
    <form>
      <a href="<%= new_user_url %>" class="btn btn-primary navbar-btn">
        Sign Up
      </a>
    </form>
  </li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>The Purple Notes</title>
  <link href='//fonts.googleapis.com/css?family=Raleway' rel='stylesheet' type='text/css'>
  <link rel="stylesheet"
        href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css"
        media="screen">
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css"
        media="screen">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/epiceditor/0.2.2/js/epiceditor.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/lodash.js/2.4.1/lodash.underscore.min.js"></script>
  <script src="//cdnjs.cloudflare.com/ajax/libs/backbone.js/1.1.2/backbone-min.js"></script>
  <%= javascript_include_tag 'application' %>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  <%= analytics_init if Rails.env.production? %>
  <%= csrf_meta_tags %>
</head>
<%= yield :body || "<body>" %>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse"
                data-target="#collapsible-nav">
          <span class="sr-only">Display navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <span class="navbar-brand">The Purple Notes: Your Notebook Replacement</span>
      </div>
      
      <div class="collapse navbar-collapse" id="collapsible-nav">
        <ul class="nav navbar-nav navbar-right">
          <%= render partial: "layouts/user_links" %>
        </ul>
      </div>
    </div>
  </nav>
  
  <div class="container">
  
  <%= render partial: "layouts/errors" %>

  <%= yield %>
  
  </div>
</body>
</html>